### ISSUE TITLE
这个是拟合不是预测吧，预测时不能用当天的数据，还是我理解错你的代码了。

### ISSUE THREAD

**Issue by ACupofAir** [PatientEz/CNN-BiLSTM-Attention-Time-Series-Prediction_Keras#1]

**Comment by YeQiuO** [comment]
作者用的是前20天的数据预测第21天，作为一条数据
因此输入维度是（20, INPUT_DIMS）

**Comment by ACupofAir** [comment]
> 作者用的是前20天的数据预测第21天，作为一条数据 因此输入维度是（20, INPUT_DIMS）

这我知道呀，用lookback长度去预测下一个时间步的；我的意思是他**预测出来的输出值并没有作为下一次预测的输入**

**Comment by alibabazzz999** [comment]
会不会是动态预测，滑窗预测。

**Comment by ACupofAir** [comment]
nope
